### ISSUE TITLE
Error LSApplicationQueriesSchemes

### ISSUE THREAD

**Issue by andykov** [msywensky/nativescript-phone#40]
I am trying to make a button, by clicking on which a mobile number will be called. The fact is that when compiling to a real device, an error occurs in the console:

`Error detected during LiveSync on [UUID] for /Users/andrey/Desktop/rentride-apps/rentride-black/rrblack. Error: Unexpected key "LSApplicationQueriesSchemes" while parsing <dict/>.`

This happened after I added the following code, according to the plugin instructions.

`<key>LSApplicationQueriesSchemes</key>
<array>
    <string>tel</string>
    <string>telprompt</string>
</array>`

What could be the reason?

I use:

- Client Sidekick
- Real device iPhone XR iOS 12

TNS doctor:
✔ Your ANDROID_HOME environment variable is set and points to correct directory.
✔ Your adb from the Android SDK is correctly installed.
✔ The Android SDK is installed.
✔ A compatible Android SDK for compilation is found.
✔ Javac is installed and is configured properly.
✔ The Java Development Kit (JDK) is installed and is configured properly.
✔ Xcode is installed and is configured properly.
✔ xcodeproj is installed and is configured properly.
✔ CocoaPods are installed.
✔ CocoaPods update is not required.
✔ CocoaPods are configured properly.
✔ Your current CocoaPods version is newer than 1.0.0.
✔ Python installed and configured correctly.
✔ The Python 'six' package is found.
✔ Xcode version 10.2.1 satisfies minimum required version 9.
✔ Getting NativeScript components versions information...
✔ Component nativescript has 5.4.2 version and is up to date.
✔ Component tns-core-modules has 5.4.3 version and is up to date.
✔ Component tns-android has 5.4.0 version and is up to date.
✔ Component tns-ios has 5.4.2 version and is up to date.

**Comment by bradmartin** [comment]
That is odd, the key is defined here on the Apple dev docs: https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/LaunchServicesKeys.html#//apple_ref/doc/uid/TP40009250-SW14

Although, after looking I haven't found `telprompt` to be listed in the values, only `tel` so far for initiating telephone calls. Maybe iOS has changed the possible values and `telprompt` is no longer valid.

What happens if you drop that value from the key array?
