### ISSUE TITLE
How to use async call?

### ISSUE THREAD

**Issue by zairwolf** [msywensky/nativescript-phone#44]
Async and await.

Thanks.

**Comment by bradmartin** [comment]
Any promise based method in JS can be used with `async/await` in most environments today.

For instance the `dial` method: 

```ts
import { dial } from 'nativescript-phone';

async function dialMom() {
    await dial('181919191');
}

```

However, not much benefit with these functions in awaiting them for a result as they were previously using callbacks and now the plugin since version 3.0.0 uses an event emitter approach for handling the success, error, failure events for SMS and Dial. See the README for more info.
