### ISSUE TITLE
Add phone permission request for Android 6

### ISSUE THREAD

**Issue by nedium** [msywensky/nativescript-phone#6]
On Android 6, dialing needs additional permission. Please add a function for displaying permission request dialog.

**Comment by bradmartin** [comment]
In my opinion this should be left to the developer to handle, not necessarily the individual plugins since not all app devs are required to target Android 6.0. Just my personal opinion and with the following plugin, that handles permissions easily in a nice JS API it's easier on the plugin authors to not worry about hard coding permission checks into their plugins: https://github.com/NathanaelA/nativescript-permissions and it works great.

**Comment by ADjenkov** [comment]
So what is the permission that is required for this plugin to run under Android 6.0 ? I cannot make it work on Android 6.0. Some advice?

**Comment by bradmartin** [comment]
Look at the NativeScript permissions plugin for a nice js API to deal with runtime permissions. You'll see in the readme how to do the right request

**Comment by bradmartin** [comment]
CALL_PHONE permission handled with 1.3.0
