### ISSUE TITLE
Plugin Not Working

### ISSUE THREAD

**Issue by zeeshanjan82** [msywensky/nativescript-phone#8]
This plugin does not seem to work for me, I am integrating this plugin in my angular2 + typescript project and I am able to import the module from node_modules also have added the required permission inside my AndroidMainifest file but the call is not initiated when I call the dial function, no error is thrown but still nothing happens I have tried on both emulator and phone.

**Comment by msywensky** [comment]
I have not tried it yet with an angular2 project.  Not sure when I will have time to look into it.  

There is a fork that adds typescript support.  Give it a shot.  https://github.com/abuda7em/nativescript-phone

**Comment by bradmartin** [comment]
I'm closing this for now. If you still have an issue please open and provide your code for using the plugin and the package.json for the app. The plugin works inside plain NativeScript and Angular/NativeScript. Shouldn't be any additional steps for it to work since it's a plain javascript plugin utilizing native apis on the platforms.
![nativephone](https://cloud.githubusercontent.com/assets/6006148/20438510/9553d678-ad7d-11e6-8b6c-1ba3039a149b.gif)
